version: '3.8'
services:
  webapp:
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080
      - DOTNET_WATCH_RESTART_ON_RUDE_EDIT=true
      - ApiSettings__KommuneInfoApiBaseUrl=https://ws.geonorge.no/kommuneinfo/v1
      - ApiSettings__StedsnavnApiBaseUrl=https://ws.geonorge.no/stedsnavn/v1
    volumes:
      - .:/app
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
    command: dotnet watch run --no-launch-profile
